//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yarik
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clients()
        {
            this.Rentals = new HashSet<Rentals>();
        }
    
        public int ID_Clients { get; set; }
        public string CompanyName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string PassportData { get; set; }
        public string ClientAddress { get; set; }
        public Nullable<int> INN { get; set; }
        public string ClientName { get; set; }
        public string ClientSurname { get; set; }
        public string ClientMiddleName { get; set; }
        public int ClientType_ID { get; set; }
        public Nullable<int> ClientRole_ID { get; set; }
    
        public virtual ClientRole ClientRole { get; set; }
        public virtual ClientType ClientType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rentals> Rentals { get; set; }
    }
}
