//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yarik
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentRentals
    {
        public int ID_EquipmentRentals { get; set; }
        public int Rentals_ID { get; set; }
        public int Equipment_ID { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Rentals Rentals { get; set; }
    }
}
