//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yarik
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenance
    {
        public int ID_Maintenance { get; set; }
        public string MaintenanceDate { get; set; }
        public int Equipment_ID { get; set; }
        public int WorkTypes_ID { get; set; }
        public int MaintenanceStatus_ID { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual MaintenanceStatus MaintenanceStatus { get; set; }
        public virtual WorkTypes WorkTypes { get; set; }
    }
}
