//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yarik
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InstrumentServicesEntities1 : DbContext
    {
        public InstrumentServicesEntities1()
            : base("name=InstrumentServicesEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientRole> ClientRole { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<ClientType> ClientType { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<EmployeesRole> EmployeesRole { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<EquipmentCategories> EquipmentCategories { get; set; }
        public virtual DbSet<EquipmentRentals> EquipmentRentals { get; set; }
        public virtual DbSet<Maintenance> Maintenance { get; set; }
        public virtual DbSet<MaintenanceStatus> MaintenanceStatus { get; set; }
        public virtual DbSet<Rentals> Rentals { get; set; }
        public virtual DbSet<WorkTypes> WorkTypes { get; set; }
    }
}
